name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.4+2
  google_sign_in: ^4.0.0
  firebase_core: ^0.3.0
  firebase_dynamic_links: ^0.2.0+3
  cloud_firestore: ^0.9.13+1
  http: ^0.12.0+2
  recase: ^2.0.1
  image_picker: ^0.5.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
      - assets/me.jpg

  fonts:
  - family: Amarillo
    fonts:
    - asset: lib/fonts/Amarillo.ttf


